site_name: WaterCS
site_author: 'Water-CS-Application'
markdown_extensions:
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
plugins:
  - search
theme:
  logo: "assets/favicon.png"
  favicon: "images/WaterCS.png"
  icon:
    repo: fontawesome/brands/github
  name: material
  custom_dir: overrides
  language: zh
  features:
    - content.action.edit
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.integrate
    - toc.follow
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: "index.md"
  - 项目介绍:
      - 申请总纲: "Application.md"
      - HK:
          - MS@HK: "Program/HK/HK_summry.md"
          - CS@CUHK: "Program/HK/T1/CS@CUHK.md"
          - IE@CUHK: "Program/HK/T1.5/IE@CUHK.md"
          - ASDS@CUHK: "Program/HK/TX/ASDS@CUHK.md"
          - BDT@HKUST: "Program/HK/T1/BDT@HKUST.md"
          - IT@HKUST: "Program/HK/T1/IT@HKUST.md"
          - CS@HKU: "Program/HK/T2/CS@HKU.md"
          - AI@HKU: "Program/HK/T1.5/AI@HKU.md"
          - DS@HKU: "Program/HK/T1.5/DS@HKU.md"
      - SG:
          - Mcomp@NUS: "Program/SG/T1/Mcomp@NUS.md"
          - Mcomp GT@NUS: "Program/SG/TX/Mcomp GT@NUS.md"
          - SE@NUS: "Program/SG/T2/SE@NUS.md"
          - IS@NUS: "Program/SG/T2/IS@NUS.md"
          - DSML@NUS: "Program/SG/T1/DSML@NUS.md"
          - FE@NUS: "Program/SG/T1/FE@NUS.md"
          - CE@NUS: "Program/SG/T1.5/CE@NUS.md"
          - AI@NTU: "Program/SG/T1/AI@NTU.md"
          - ISE@NUS: "Program/SG/T2/ISE@NUS.md"
          - CyberSec@NTU: "Program/SG/T1.5/CyberSec@NTU.md"
          - BlockChain@NTU: "Program/SG/T1.5/BlockChain@NTU.md"
          - DS@NTU: "Program/SG/T1/DS@NTU.md"
          - CCA@NTU: "Program/SG/T2/CCA@NTU.md"
          - SPML@NTU: "Program/SG/T2/SPML@NTU.md"
repo_url: https://github.com/Water-CS-Application/WaterCS
repo_name: WaterCS
edit_uri: edit/main/docs/
extra:
  homepage: https://github.com/Water-CS-Application/WaterCS
  consent:
      title: Cookie consent
      description: >-
        We use cookies to recognize your repeated visits and preferences, as well
        as to measure the effectiveness of our documentation and whether users
        find what they're searching for. With your consent, you're helping us to
        make our documentation better.
      actions:
        - accept
        - manage
